### ISSUE TITLE
Node dns config

### ISSUE THREAD

**Issue by jmatsushita** [apparatus/fuge-dns#4]
Hi there,

What's the recommendation for hooking up dns resolution to the fuge provided dns? System level? Somehow override node's resolution? On a per process or package basis?

Cheers,

Jun

**Comment by pelger** [comment]
We have a module for that: https://github.com/apparatus/concordant

For a usage example see: https://github.com/apparatus/fuge-examples/blob/master/kubernets-emulation.

Hope that helps!
